#!/usr/bin/env bash
#
# GLM5 Chad Arch Installer - Snapper Configuration
#

set -eo pipefail

if [[ -z "${_SNAPPER_LOADED:-}" ]]; then
    readonly _SNAPPER_LOADED=1
else
    return 0
fi

SNAPPER_CONFIG_DIR="${SNAPPER_CONFIG_DIR:-/etc/snapper/configs}"
SNAPPER_CONFIG_TEMPLATE="${SNAPPER_CONFIG_TEMPLATE:-/usr/share/snapper/config-templates/default}"

snapper_create_config() {
    local config_name="$1"
    local subvolume="${2:-/}"
    local fstype="${3:-btrfs}"
    
    _log_section "Creating Snapper Config: $config_name"
    
    log_info "Creating snapper config for $subvolume"
    
    if [[ "$MOCK_MODE" == "true" ]]; then
        mkdir -p "$MOCK_ROOT$SNAPPER_CONFIG_DIR"
        mock_cmd "Create snapper config" snapper -c "$config_name" create-config -f "$fstype" "$subvolume"
    else
        if ! snapper -c "$config_name" create-config -f "$fstype" "$subvolume" 2>/dev/null; then
            log_warn "Snapper config $config_name may already exist"
        fi
    fi
}

snapper_configure() {
    local config_name="$1"
    local subvolume="${2:-/}"
    
    _log_section "Configuring Snapper: $config_name"
    
    local config_file
    if [[ "$MOCK_MODE" == "true" ]]; then
        config_file="$MOCK_ROOT$SNAPPER_CONFIG_DIR/$config_name"
    else
        config_file="$SNAPPER_CONFIG_DIR/$config_name"
    fi
    
    local hourly daily weekly monthly yearly
    hourly=$(config_get "snapper.hourly" "10")
    daily=$(config_get "snapper.daily" "7")
    weekly=$(config_get "snapper.weekly" "4")
    monthly=$(config_get "snapper.monthly" "6")
    yearly=$(config_get "snapper.yearly" "2")
    
    local snapper_config="# Generated by GLM5 Chad Arch Installer
# Configuration for $config_name

SUBVOLUME=\"$subvolume\"
FSTYPE=\"btrfs\"

# Space limits
SPACE_LIMIT=\"0.5\"
FREE_LIMIT=\"0.2\"

# Enable automatic timeline snapshots
TIMELINE_CREATE=\"yes\"
TIMELINE_CLEANUP=\"yes\"

# Timeline retention
TIMELINE_LIMIT_HOURLY=\"$hourly\"
TIMELINE_LIMIT_DAILY=\"$daily\"
TIMELINE_LIMIT_WEEKLY=\"$weekly\"
TIMELINE_LIMIT_MONTHLY=\"$monthly\"
TIMELINE_LIMIT_YEARLY=\"$yearly\"

# Numbered snapshots (pre/post for package installs)
NUMBER_CLEANUP=\"yes\"
NUMBER_MIN_AGE=\"1800\"
NUMBER_LIMIT=\"50\"
NUMBER_LIMIT_IMPORTANT=\"20\"

# Empty pre-post cleanup
EMPTY_PRE_POST_CLEANUP=\"yes\"
EMPTY_PRE_POST_MIN_AGE=\"1800\"
"
    
    mock_write_file "$config_file" "$snapper_config"
    
    log_info "Snapper config written to $config_file"
}

snapper_enable_timeline() {
    log_info "Enabling snapper timeline services"
    
    if [[ "$MOCK_MODE" == "true" ]]; then
        mock_cmd "Enable snapper-timeline" systemctl enable snapper-timeline.timer
        mock_cmd "Enable snapper-cleanup" systemctl enable snapper-cleanup.timer
        mock_cmd "Start snapper-timeline" systemctl start snapper-timeline.timer
        mock_cmd "Start snapper-cleanup" systemctl start snapper-cleanup.timer
    else
        systemctl enable --now snapper-timeline.timer
        systemctl enable --now snapper-cleanup.timer
    fi
}

snapper_create_snapshot() {
    local config_name="${1:-root}"
    local description="${2:-Manual snapshot}"
    local cleanup="${3:-number}"
    
    log_info "Creating snapshot: $description"
    
    if [[ "$MOCK_MODE" == "true" ]]; then
        mock_cmd "Create snapshot" snapper -c "$config_name" create --cleanup-algorithm="$cleanup" --description "$description"
    else
        snapper -c "$config_name" create --cleanup-algorithm="$cleanup" --description "$description"
    fi
}

snapper_create_pre_post() {
    local config_name="${1:-root}"
    local description="${2:-Package operation}"
    
    log_debug "Creating pre-snapshot: $description"
    
    local pre_num
    if [[ "$MOCK_MODE" == "true" ]]; then
        mock_cmd "Create pre-snapshot" snapper -c "$config_name" create -t pre --cleanup-algorithm=number --description "$description"
        pre_num="mock"
    else
        pre_num=$(snapper -c "$config_name" create -t pre --cleanup-algorithm=number --print-number --description "$description")
    fi
    
    echo "$pre_num"
}

snapper_create_post() {
    local config_name="${1:-root}"
    local pre_num="${2:-}"
    local description="${3:-Package operation}"
    
    log_debug "Creating post-snapshot: $description"
    
    if [[ -n "$pre_num" ]]; then
        mock_cmd "Create post-snapshot" snapper -c "$config_name" create -t post --cleanup-algorithm=number --pre-number="$pre_num" --description "$description"
    else
        mock_cmd "Create post-snapshot" snapper -c "$config_name" create -t post --cleanup-algorithm=number --description "$description"
    fi
}

snapper_list() {
    local config_name="${1:-root}"
    
    snapper -c "$config_name" list 2>/dev/null || echo "No snapshots found"
}

snapper_rollback() {
    local config_name="${1:-root}"
    local snapshot_num="$2"
    
    log_info "Rolling back to snapshot #$snapshot_num"
    
    if [[ "$MOCK_MODE" == "true" ]]; then
        mock_cmd "Rollback to snapshot" snapper -c "$config_name" rollback "$snapshot_num"
    else
        snapper -c "$config_name" rollback "$snapshot_num"
    fi
}

snapper_delete() {
    local config_name="${1:-root}"
    local snapshot_num="$2"
    
    log_info "Deleting snapshot #$snapshot_num"
    
    mock_cmd "Delete snapshot" snapper -c "$config_name" delete "$snapshot_num"
}

snapper_setup_pacman_hooks() {
    local hooks_dir="${1:-/etc/pacman.d/hooks}"
    
    _log_section "Setting up Pacman Hooks for Snapshots"
    
    local pre_hook="[Trigger]
Operation = Install
Operation = Upgrade
Operation = Remove
Type = Package
Target = *

[Action]
Description = Creating pre-snapshot before pacman operation...
Depends = snapper
When = PreExecution
Exec = /usr/bin/snapper -c root create -t pre --cleanup-algorithm=number --description \"pacman: pre\"
"
    
    local post_hook="[Trigger]
Operation = Install
Operation = Upgrade
Operation = Remove
Type = Package
Target = *

[Action]
Description = Creating post-snapshot after pacman operation...
Depends = snapper
When = PostTransaction
Exec = /usr/bin/snapper -c root create -t post --cleanup-algorithm=number --description \"pacman: post\"
"
    
    if [[ "$MOCK_MODE" == "true" ]]; then
        mkdir -p "$MOCK_ROOT$hooks_dir"
        mock_write_file "$hooks_dir/50-snapper-pre.hook" "$pre_hook"
        mock_write_file "$hooks_dir/50-snapper-post.hook" "$post_hook"
    else
        mkdir -p "$hooks_dir"
        echo "$pre_hook" > "$hooks_dir/50-snapper-pre.hook"
        echo "$post_hook" > "$hooks_dir/50-snapper-post.hook"
    fi
    
    log_info "Pacman snapshot hooks installed"
}

snapper_install_grub_btrfs() {
    _log_section "Installing grub-btrfs for Bootable Snapshots"
    
    if [[ "$MOCK_MODE" == "true" ]]; then
        mock_cmd "Install grub-btrfs" pacman -S --noconfirm grub-btrfs
        mock_cmd "Enable grub-btrfsd" systemctl enable grub-btrfsd
    else
        pacman -S --noconfirm grub-btrfs 2>/dev/null || true
        systemctl enable grub-btrfsd 2>/dev/null || true
    fi
    
    log_info "grub-btrfs installed - snapshots will be bootable from GRUB"
}

snapper_get_config() {
    local config_name="${1:-root}"
    
    if [[ "$MOCK_MODE" == "true" ]]; then
        cat "$MOCK_ROOT$SNAPPER_CONFIG_DIR/$config_name" 2>/dev/null || echo "Config not found"
    else
        cat "$SNAPPER_CONFIG_DIR/$config_name" 2>/dev/null || echo "Config not found"
    fi
}

snapper_validate_config() {
    local config_name="${1:-root}"
    local config_file
    
    if [[ "$MOCK_MODE" == "true" ]]; then
        config_file="$MOCK_ROOT$SNAPPER_CONFIG_DIR/$config_name"
    else
        config_file="$SNAPPER_CONFIG_DIR/$config_name"
    fi
    
    if [[ ! -f "$config_file" ]]; then
        log_error "Snapper config not found: $config_file"
        return 1
    fi
    
    local required_keys=(
        "SUBVOLUME"
        "FSTYPE"
        "TIMELINE_CREATE"
        "TIMELINE_CLEANUP"
        "NUMBER_CLEANUP"
    )
    
    local errors=0
    for key in "${required_keys[@]}"; do
        if ! grep -q "^$key=" "$config_file"; then
            log_error "Missing required key: $key"
            ((errors++))
        fi
    done
    
    if [[ $errors -eq 0 ]]; then
        log_info "Snapper config $config_name is valid"
        return 0
    else
        return 1
    fi
}

snapper_full_setup() {
    local root_subvol="${1:-/}"
    local home_subvol="${2:-/home}"
    
    _log_section "Full Snapper Setup"
    
    snapper_create_config "root" "$root_subvol"
    snapper_configure "root" "$root_subvol"
    
    if [[ -d "$home_subvol" ]]; then
        snapper_create_config "home" "$home_subvol"
        snapper_configure "home" "$home_subvol"
    fi
    
    snapper_setup_pacman_hooks
    
    local bootloader
    bootloader=$(config_get "boot.loader" "systemd-boot")
    
    if [[ "$bootloader" == "grub" ]]; then
        snapper_install_grub_btrfs
    fi
    
    log_info "Snapper setup complete"
}
